.job_template: &fix_gopath
  before_script:
    # Create a symlink under $GOPATH, this is needed for local build
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME

stages:
  - build
  - package
  - deploy

build_job:
  <<: *fix_gopath
  image: golang:1.11-stretch
  stage: build
  script:
  - make
  artifacts:
    paths:
      - document-imaging

deb_package_job:
  <<: *fix_gopath
  image: golang:1.11-stretch
  stage: package
  script:
  - apt-get update
  - apt-get install -y devscripts build-essential
  - make package
  artifacts:
    paths:
      - package/*.deb
      - package/*.tar.gz

snap_package_job:
  image: snapcore/snapcraft:latest
  stage: package
  before_script:
  - apt-get update
  script:
  - snapcraft
  artifacts:
    paths:
      - document-imaging*.snap

snap_deploy_job:
  image: snapcore/snapcraft:latest
  stage: deploy
  before_script:
  - apt-get update
  script:
  - mkdir -p .snapcraft
  - echo $SNAPCRAFT_KEY | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
  - snapcraft push *.snap
  - snapcraft list-revisions document-imaging
  - REV=$(snapcraft list-revisions document-imaging | sed -n '3 p' | awk 'END {print $1}')
  - echo $REV
  - snapcraft release document-imaging $REV edge
  dependencies:
    - snap_package_job
  only:
    - master