image: docker:latest

variables:
  DOCKER_DRIVER: overlay

before_script:
  - mkdir -p /go/src/gitlab.com/countableset/document-imaging
  - cp -r /builds/countableset/document-imaging/ /go/src/gitlab.com/countableset/
  - cd /go/src/gitlab.com/countableset/document-imaging

stages:
  - build
  - package
  - snap

build_job:
  image: golang:latest
  stage: build
  script:
  - make

deb_package_job:
  image: golang:latest
  stage: package
  script:
  - apt-get update
  - apt-get install -y devscripts build-essential
  - make package

snap_package_job:
  image: snapcore/snapcraft:latest
  stage: snap
  script:
  - snapcraft
  - mkdir -p .snapcraft
  - openssl aes-256-cbc -d -in snap/snapcraft.encrypted -out .snapcraft/snapcraft.cfg -k $SNAPCRAFT_KEY
  - snapcraft push *.snap
  - snapcraft list-revisions document-imaging
  - snapcraft list-revisions document-imaging | sed -n '2 p' | awk 'END {print $1}'
  - snapcraft release document-imaging $(snapcraft list-revisions document-imaging | sed -n '2 p' | awk 'END {print $1}') edge
