image: golang:latest

before_script:
    - apt-get update
    - apt-get install -y devscripts build-essential
    - mkdir -p /go/src/gitlab.com/countableset/document-imaging
    - cp -r /builds/countableset/document-imaging/ /go/src/gitlab.com/countableset/
    - cd /go/src/gitlab.com/countableset/document-imaging

stages:
    - build

default:
    stage: build
    script:
        - make

package:
    stage: build
    script:
        - make package
