name: document-imaging
version: v0.3.0
summary: scans documents
description: scanning utility written in go using imagemagick, libtiff-tools, and sane-utils

grade: devel
confinement: strict

parts:
  document-imaging:
    source: .
    source-tag: 'v0.3.0'
    plugin: go
    go-importpath: gitlab.com/countableset/document-imaging
    build: make fmt test install
    # install: |
    #   echo "net\ngenesys" > $SNAPCRAFT_PART_INSTALL/etc/sane.d/dll.conf
    #   echo "localhost" > $SNAPCRAFT_PART_INSTALL/etc/sane.d/net.conf
    stage-packages:
      - libtiff-tools
      # - sane-utils

  sane-utils:
    plugin: autotools
    source: https://gitlab.com/sane-project/backends.git
    source-type: git
    source-tag: RELEASE_1_0_25
    configflags:
      - --prefix=/opt/sane-utils
    install: |
      echo "net\ngenesys" > $SNAPCRAFT_PART_INSTALL/opt/sane-utils/etc/sane.d/dll.conf
      echo "localhost" > $SNAPCRAFT_PART_INSTALL/opt/sane-utils/etc/sane.d/net.conf
    build-packages:
      - libusb-dev

  imagemagick:
    plugin: autotools
    source: https://github.com/ImageMagick/ImageMagick.git
    source-type: git
    source-tag: 7.0.8-14
    configflags:
      - --prefix=/opt/imagemagick
      - --enable-static=yes
      - --enable-shared=yes
      - --disable-docs
      - --disable-deprecated
      - --without-autotrace
      - --without-bzlib
      - --without-djvu
      - --without-dps
      - --without-fftw
      - --without-fontconfig
      - --without-fpx
      - --without-freetype
      - --without-gvc
      - --without-jbig
      - --without-jpeg
      - --without-lcms
      - --without-lzma
      - --without-magick-plus-plus
      - --without-mpeg
      - --without-openexr
      - --without-openjp2
      - --without-pango
      - --without-png
      - --without-raqm
      - --without-webp
      - --without-wmf
      - --without-x
      - --without-xml
      - --with-tiff=yes
    build-packages:
      - libtiff5-dev

apps:
  document-imaging:
    command: document-imaging
    plugs: [network, home, raw-usb]
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin:$SNAP/opt/imagemagick/bin:$SNAP/opt/sane-utils/bin:$PATH
      # PATH: $SNAP/usr/bin:$SNAP/bin:$SNAP/opt/imagemagick/bin:$PATH
      # LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/sane:$SNAP/opt/imagemagick/lib
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/opt/sane-utils/lib:$SNAP/opt/sane-utils/lib/sane:$SNAP/opt/imagemagick/lib
      MAGICK_CONFIGURE_PATH: $SNAP/opt/imagemagick/etc/ImageMagick-6:$SNAP/opt/imagemagick/share/ImageMagick-6:$SNAP/opt/imagemagick/lib/ImageMagick-6.9.9/config-Q16
      MAGICK_HOME: $SNAP/opt/imagemagick
      SANE_CONFIG_DIR: $SNAP/opt/sane-utils/etc/sane.d
      # SANE_CONFIG_DIR: $SNAP/etc/sane.d
      DOCUMENT_CONFIG_HOME: $SNAP_USER_DATA
